"""Bundle an LLM agent + programmatic floor into ONE file for Kaggle.

The competition framework loads a single agents/templates/my_agent.py.
This inlines: v79 programmatic agent (as ProgAgent), the renderer, the
LLM client, and the chosen LLM agent -> a bundle exposing class MyAgent.

Builds TWO bundles:
  my_agent_llm.py      <- llm/agent.py         (rescue design; LLM on stall)
  my_agent_primary.py  <- llm/agent_primary.py (Duck-style; LLM drives)
"""
import ast
import io
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent


def read(p):
    return io.open(HERE / p, encoding="utf-8").read()


HEADER = (
    '"""ARC-AGI-3 LLM agent (bundled): LLM agent + v79 programmatic floor.\n'
    'Generated by build_llm_bundle.py — do not edit directly."""\n'
    "from __future__ import annotations\n"
    "import os, re, sys, time, json, zlib, random, urllib.request, threading\n"
    "from collections import defaultdict, deque\n"
    "from typing import Any, Optional\n"
    "from arcengine import FrameData, GameAction, GameState\n"
    "from agents.agent import Agent\n\n"
)


def build(agent_src: str, out_name: str) -> None:
    # 1) programmatic agent (v79) — MyAgent -> ProgAgent, drop its Agent import
    prog = read("my_agent.py")
    prog = prog.replace("from agents.agent import Agent\n", "")
    prog = re.sub(r"\bclass MyAgent\(Agent\):", "class ProgAgent(Agent):", prog)

    # 2) renderer + 3) llm client — dependency-free (transformers lazy).
    render = read("llm/render.py")
    client = read("llm/llm_client.py")

    # 4) llm agent — strip its imports of render/llm_client/my_agent (inlined)
    agent = read(agent_src)
    for pat in [
        r"^import render as _render.*$",
        r"^import llm_client as _llmc.*$",
        r"^_HERE = .*$", r"^sys\.path\.insert.*$",
        r"^import importlib\.util as _ilu.*$",
        r"^_spec = _ilu\.spec_from_file_location\([\s\S]*?ProgAgent = _prog\.MyAgent",
        r"^from pathlib import Path.*$",
    ]:
        agent = re.sub(pat, "", agent, flags=re.M)
    # rewire module-qualified refs to the inlined top-level names
    agent = agent.replace("_render.", "").replace("_llmc.", "")

    # de-duplicate imports that the header already provides
    for mod in (prog, render, client, agent):
        pass
    prog = prog.replace("from __future__ import annotations\n", "")
    render = render.replace("from __future__ import annotations\n", "")
    client = client.replace("from __future__ import annotations\n", "")
    agent = agent.replace("from __future__ import annotations\n", "")
    agent = re.sub(r"^from arcengine import .*$", "", agent, flags=re.M)
    agent = re.sub(r"^from agents\.agent import Agent$", "", agent, flags=re.M)

    bundle = (
        HEADER
        + "# ===== programmatic floor (v79) =====\n" + prog + "\n\n"
        + "# ===== renderer =====\n" + render + "\n\n"
        + "# ===== llm client =====\n" + client + "\n\n"
        + "# ===== llm agent =====\n" + agent + "\n"
    )
    out = HERE / out_name
    out.write_text(bundle, encoding="utf-8")
    ast.parse(bundle)
    print(f"wrote {out} ({len(bundle.splitlines())} lines) — syntax OK")


if __name__ == "__main__":
    build("llm/agent.py", "my_agent_llm.py")
    build("llm/agent_primary.py", "my_agent_primary.py")
