"""Generate arc_colab_eval.ipynb from arc_colab_eval.py.

The notebook clones the repo at run time, so opening it in Colab always
runs the LATEST agent code. Regenerated by CI on every push.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
code = (HERE / "arc_colab_eval.py").read_text(encoding="utf-8")

md = (
    "# ARC-AGI-3 LLM-PRIMARY GPU Eval (Colab)\n\n"
    "Tests whether an LLM **driving** the game (Duck-style) beats the "
    "programmatic floor. The LLM solves by *reasoning about the board*, so "
    "success here should transfer to the private set — unlike the "
    "heuristic tricks that plateaued at LB 0.27.\n\n"
    "1. **Runtime -> Change runtime type -> GPU.** Prefer **L4** (runs a 14B) "
    "or **A100** (32B). T4 falls back to a 7B and is only a smoke test.\n"
    "2. Run the cell below. It clones the latest code, installs vLLM, serves "
    "a quantized Qwen2.5 (AWQ) sized to the GPU, and evaluates the "
    "**LLM-primary agent vs the programmatic floor** on the 25 public "
    "games. If vLLM fails to start it prints the server log so we can see "
    "why.\n"
    "3. Copy the printed **RESULT** block back to Claude Code.\n\n"
    "_Auto-generated on every commit; always pulls the latest agent from "
    "GitHub. Optional: add an `HF_TOKEN` Colab secret for faster model "
    "downloads._"
)

nb = {
    "cells": [
        {"cell_type": "markdown", "metadata": {}, "source": md},
        {"cell_type": "code", "metadata": {}, "execution_count": None,
         "outputs": [], "source": code},
    ],
    "metadata": {
        "accelerator": "GPU",
        "colab": {"provenance": [], "gpuType": "T4"},
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "language_info": {"name": "python"},
    },
    "nbformat": 4, "nbformat_minor": 0,
}
out = HERE / "arc_colab_eval.ipynb"
out.write_text(json.dumps(nb, indent=1), encoding="utf-8")
print("wrote", out)
