"""Generate arc_colab_eval.ipynb from arc_colab_eval.py.

The notebook clones the repo at run time, so opening it in Colab always
runs the LATEST agent code. Regenerated by CI on every push.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
code = (HERE / "arc_colab_eval.py").read_text(encoding="utf-8")

md = (
    "# ARC-AGI-3 LLM-Agent GPU Eval (Colab)\n\n"
    "1. **Runtime -> Change runtime type -> GPU** (L4 or A100 for the 7B; "
    "T4 falls back to 3B).\n"
    "2. Run the cell below. It clones the latest code, installs vLLM, "
    "serves the model, and evaluates the **LLM rescue-agent vs the "
    "programmatic floor** on the 25 public games.\n"
    "3. Copy the printed **RESULT** block back to Claude Code.\n\n"
    "_This notebook is auto-generated on every commit; it always pulls the "
    "latest agent from GitHub._"
)

nb = {
    "cells": [
        {"cell_type": "markdown", "metadata": {}, "source": md},
        {"cell_type": "code", "metadata": {}, "execution_count": None,
         "outputs": [], "source": code},
    ],
    "metadata": {
        "accelerator": "GPU",
        "colab": {"provenance": [], "gpuType": "T4"},
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "language_info": {"name": "python"},
    },
    "nbformat": 4, "nbformat_minor": 0,
}
out = HERE / "arc_colab_eval.ipynb"
out.write_text(json.dumps(nb, indent=1), encoding="utf-8")
print("wrote", out)
