"""Bundle the LLM agent + programmatic floor into ONE file for Kaggle.

The competition framework loads a single agents/templates/my_agent.py.
This inlines: v79 programmatic agent (as ProgAgent), the renderer, the
LLM client, and the LLM agent -> my_agent_llm.py exposing class MyAgent.
"""
import io
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "my_agent_llm.py"


def read(p):
    return io.open(HERE / p, encoding="utf-8").read()


# 1) programmatic agent (v79) — rename class MyAgent -> ProgAgent, strip its
#    module-level `from agents.agent import Agent` (we keep one at the top).
prog = read("my_agent.py")
prog = prog.replace("from agents.agent import Agent\n", "")
prog = re.sub(r"\bclass MyAgent\(Agent\):", "class ProgAgent(Agent):", prog)

# 2) renderer — drop nothing, it's dependency-free.
render = read("llm/render.py")

# 3) llm client — dependency-free (transformers imported lazily inside).
client = read("llm/llm_client.py")

# 4) llm agent — strip its imports of render/llm_client/my_agent (now inline)
agent = read("llm/agent.py")
for pat in [
    r"^import render as _render.*$",
    r"^import llm_client as _llmc.*$",
    r"^_HERE = .*$", r"^sys\.path\.insert.*$",
    r"^import importlib\.util as _ilu.*$",
    r"^_spec = _ilu\.spec_from_file_location\([\s\S]*?ProgAgent = _prog\.MyAgent",
    r"^from pathlib import Path.*$",
]:
    agent = re.sub(pat, "", agent, flags=re.M)
# rewire references: _render.X -> X, _llmc.X -> X, ProgAgent already inlined
agent = agent.replace("_render.render_observation", "render_observation")
agent = agent.replace("_llmc.make_client", "make_client")
agent = agent.replace("_llmc.LLMUnavailable", "LLMUnavailable")
# remove the duplicate future import / arcengine import lines from agent
agent = agent.replace("from __future__ import annotations\n", "")
agent = re.sub(r"^from arcengine import .*$", "", agent, flags=re.M)
agent = re.sub(r"^from agents\.agent import Agent$", "", agent, flags=re.M)

prog = prog.replace("from __future__ import annotations\n", "")
render = render.replace("from __future__ import annotations\n", "")
client = client.replace("from __future__ import annotations\n", "")

header = (
    '"""ARC-AGI-3 LLM agent (bundled): LLM tool-agent + v79 programmatic '
    'floor.\nGenerated by build_llm_bundle.py — do not edit directly."""\n'
    "from __future__ import annotations\n"
    "import os, re, sys, time, json, zlib, random, urllib.request\n"
    "from collections import defaultdict, deque\n"
    "from typing import Any, Optional\n"
    "from arcengine import FrameData, GameAction, GameState\n"
    "from agents.agent import Agent\n\n"
)

bundle = (
    header
    + "# ===== programmatic floor (v79) =====\n" + prog + "\n\n"
    + "# ===== renderer =====\n" + render + "\n\n"
    + "# ===== llm client =====\n" + client + "\n\n"
    + "# ===== llm agent =====\n" + agent + "\n"
)

# ProgAgent reference inside agent.py used the import; ensure it points to
# the inlined class.
bundle = bundle.replace("self.prog = ProgAgent(*a, **k)",
                        "self.prog = ProgAgent(*a, **k)")

OUT.write_text(bundle, encoding="utf-8")
import ast
ast.parse(bundle)
print(f"wrote {OUT} ({len(bundle.splitlines())} lines) — syntax OK")
